# -*- coding: utf-8 -*-
"""Copy of PA (Q3) by Praise Yakubu

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1x7HUW8UZq5NQUspD4ZMXCx7toMXNbu0x
"""

def validate_number():
    while True:
        try:
            number = float(input("Enter a number: "))
            break  # Break the loop if input is valid
        except ValueError:
            print("Error: Please enter a valid number.")

    return number

def get_integer_input(prompt):
    while True:
        try:
            value = int(input(prompt))
            break  # Break the loop if input is valid
        except ValueError:
            print("Error: Please enter a valid integer.")

    return value

# Welcome message
print("#################################")
print("WELCOME TO THE DBS CONSOLE")
print("#################################")

# Enters the number of elements
num_elements = get_integer_input("Input the number of elements to be stored in the list: ")

# Initialize an empty list to store user input
user_list = []

# User input elements form this list
for i in range(num_elements):
    element = validate_number()
    user_list.append(element)

# Display the entered list
print("The elements entered in the list:")
for i, element in enumerate(user_list):
    print(f"Element-{i}: {element}")

#  Count howmany times a frequency occurs.
frequency_dict = {}
for element in user_list:
    frequency_dict[element] = frequency_dict.get(element, 0) + 1

# Display the frequency of each element
print("The frequency of all elements of the list:")
for key, value in frequency_dict.items():
    print(f"{key} occurs {value} times")